export const GET_CHARACTERS_INIT = 'GET_CHARACTERS_INIT';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export const ADD_FAV_CHARACTER_INIT = 'ADD_FAV_CHARACTER_INIT';
export const ADD_FAV_CHARACTER_SUCCESS = 'ADD_FAV_CHARACTER_SUCCESS';
export const ADD_FAV_CHARACTER_ERROR = 'ADD_FAV_CHARACTER_ERROR';